### ISSUE TITLE
builtinコマンド後のステータス確認

### ISSUE THREAD

**Issue by osorosia** [osorosia/minishell#10]
一部のbuiltinコマンド実行後のステータス確認が不足している様子。
(確認したのはcd)

逐一`echo $?`を追加すること、
`echo $?`が0以外になるようなテストケースの追加をお願いします。
- [x] echo
- [x] cd
- [x] pwd
- [x] export
- [x] unset
- [x] env
- [x] exit

**Comment by osorosia** [comment]
exitはOK

**Comment by NIhkCK** [comment]
基本的に全てのコマンドの終了ステータスを確認できるように変更しました。

**Comment by osorosia** [comment]
2点、指摘あります。
①
builtin直後に`echo $?`を追加するようにしてください。
cdのテストだと、cdではなくpwdの終了ステータスの確認になっています。
②
echoのステータス確認はecho.test内で実施してください。
（現状はecho.test以外でechoのテストをしてる？）
他のbuiltinも同様。
