### ISSUE TITLE
`$PWD`, `$OLDPWD`のテストを追加

### ISSUE THREAD

**Issue by osorosia** [osorosia/minishell#11]
`cd`を実行すると`$PWD`, `$OLDPWD`がセットされるので、そのテストを追加する

**Comment by NIhkCK** [comment]
`cd.test`
にあるテストと全く同じものをテストとし、そのコマンドを実行したのちに、
`env | grep PWD`
とし、$PWDもしくは、$OLDPWDを確認できるようにしました。
また、envの動作であると判断し、env.testに追加しました。
