### ISSUE TITLE
test上で`export`のsortをしていない

### ISSUE THREAD

**Issue by osorosia** [osorosia/minishell#12]
- export.testの1行目で単に`export`を実行しているが、表示順は合わせないのでsortをする。
他も同じように修正する。

- bashとminishellで異なる環境変数も消しておく。

e.g.)
`env | grep -v '^SHLVL=' | grep -v '^_=' | sort`

**Comment by NIhkCK** [comment]
env.testに関しても同様の症状でしたので修正します
