### ISSUE TITLE
引数ありのexportはパイプしない

### ISSUE THREAD

**Issue by osorosia** [osorosia/minishell#24]
export.testについて、exportに引数がある場合はパイプをつけないようにお願いします。
下記の動作を比較してみてください。

```sh
export = | true
echo $?

export =
echo $?
```

**Comment by NIhkCK** [comment]
statusを取るときにパイプの1番右のステータスを取ることに他のも注意してみてみます。

**Comment by NIhkCK** [comment]
export = | trueのようにするとnot a valid identifierとなってしまってexportのテストができていなかったこと確認できました。修正します。
