### ISSUE TITLE
envの`$?`のテストを追加

### ISSUE THREAD

**Issue by osorosia** [osorosia/minishell#27]
下記だと`$?`はsortの終了ステータスがセットされています。
builtin以外はstatus関係のテストで実施したいので`echo $?`削除してください。

```sh
env | grep -v '^SHLVL=' | grep -v '^_=' | sort
echo $?  # <- 削除
```

代わりに下記テストの追加をお願いします。
exportにも同様に追加をお願いします。
```sh
env > /dev/null
echo $?
```

**Comment by NIhkCK** [comment]
envの標準出力をゴミ箱に入れて、その終了ステータスを取るということがよくわかっていないので、MTGのタイミングで確認しようと思います。テストに関しては追加しておきます。
